- name: "Create basic settings for Cisco routers"
  become: yes
  hosts: routers
  tasks:
    - name: Save running to startup when modified
      ios_config:
      save_when: modified

    - name: "Configure hostname from inventory"
      ios_config:
        lines:
          - hostname {{ inventory_hostname }}

    - name: "Set IP address to GigabitEthernet2"
      ios_config:
        parents:
          - "interface GigabitEthernet2"
        lines:
          - ip address 10.0.0.1 255.255.255.252
          - no shutdown

    - name: "ospf network 10.0.0.1"
      ios_config:
        parents:
          - "router ospf 1"
        lines:
          - network 10.0.0.0 0.0.0.3 area 0
