- name: "Create basic settings for Cisco routers"
  become: yes
  hosts: routers
  tasks:
     
    - name: "Configure hostname from inventory"
      ios_config:
        lines:
          - hostname {{ inventory_hostname }}

    - name: "Set IP address to GigabitEthernet2"
      ios_config:
        parents:
          - "interface GigabitEthernet2"
        lines:
          - ip address 192.168.10.1 255.255.255.0
          - no shutdown

    - name: "ospf network 192.168.10.0"
      ios_config:
        parents:
          - "router ospf 1"
        lines:
          - network 192.168.10.0 0.0.0.255 area 0
      
    - name: "DHCP network 192.168.10.0"
      ios_config:
        parents:
          - "ip dhcp pool dhcpPoolGi2"
        lines:
          - network 192.168.10.0 255.255.255.0
          - default-router 192.168.10.1
          - dns-server 192.168.10.1
          - domain-name 192.168.10.1
          - ip dhcp excluded-address 192.168.10.1 192.168.10.50


    - name: "Backup running-config"
      ios_config:
        commands:
          - do show run
      register: running_config

    - name: "Save running-config to file"
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "./backup/{{ inventory_hostname }}-running-config.txt"

